"""SiteConfig — per-domain crawler settings generated by LLM and cached as JSON."""
from __future__ import annotations

from pathlib import Path

from pydantic import BaseModel

_DEFAULT_CONFIG_DIR = Path("data/crawler-configs")


class SiteConfig(BaseModel):
    domain: str
    site_type: str = "forum"
    needs_js: bool = False
    has_cloudflare: bool = False
    list_selector: str = ""
    title_selector: str = ""
    author_selector: str = ""
    time_selector: str = ""
    content_selector: str = ""
    comment_selector: str = ""
    next_page_selector: str = ""
    created_at: str = ""

    def save(self, config_dir: Path = _DEFAULT_CONFIG_DIR) -> Path:
        config_dir.mkdir(parents=True, exist_ok=True)
        path = config_dir / f"{self.domain}.json"
        path.write_text(self.model_dump_json(indent=2), encoding="utf-8")
        return path

    @classmethod
    def load(cls, domain: str, config_dir: Path = _DEFAULT_CONFIG_DIR) -> SiteConfig | None:
        path = config_dir / f"{domain}.json"
        if not path.exists():
            return None
        try:
            return cls.model_validate_json(path.read_text(encoding="utf-8"))
        except Exception:
            return None
